[package]
name = "cirko"
version = "0.1.1"
edition = "2024"

[[bin]]
name = "ћирко"
path = "src/main.rs"

[dependencies]
clap = "4.5.41"
once_cell = "1.21.3"
phf = { version = "0.12.1", features = ["macros"] }
regex = "1.11.1"
